apiVersion: apps/v1
kind: Deployment
metadata:
  name: parish-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parish-manager
  template:
    metadata:
      labels:
        app: parish-manager
    spec:
      containers:
      - name: parish-manager
        image: servantcode/parish-manager
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: http
          failureThreshold: 10
          periodSeconds: 30
        resources:
          limits:
            memory: "200Mi"
        env:
        - name: ES_JAVA_OPTS 
          value: "-Xmx128m -Xms128m"
---
kind: Service
apiVersion: v1
metadata:
  name: parish-manager
spec:
  selector:
    app: parish-manager
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
